# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.3.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QPushButton,
    QSizePolicy, QToolButton, QVBoxLayout, QWidget)

class Form_mainWindow(object):
    def setupUi(self, Form_mainWindow):
        if not Form_mainWindow.objectName():
            Form_mainWindow.setObjectName(u"Form_mainWindow")
        Form_mainWindow.resize(626, 474)
        self.verticalLayoutWidget = QWidget(Form_mainWindow)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(0, 0, 641, 491))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.Principal_panel_widget = QWidget(self.verticalLayoutWidget)
        self.Principal_panel_widget.setObjectName(u"Principal_panel_widget")
        self.Principal_panel_widget.setMaximumSize(QSize(639, 489))
        self.Principal_panel_widget.setStyleSheet(u"backgorund:white;")
        self.frame_encabezado = QFrame(self.Principal_panel_widget)
        self.frame_encabezado.setObjectName(u"frame_encabezado")
        self.frame_encabezado.setGeometry(QRect(0, 0, 641, 31))
        self.frame_encabezado.setMaximumSize(QSize(641, 31))
        self.frame_encabezado.setStyleSheet(u"background:rgb(170, 0, 0)")
        self.frame_encabezado.setFrameShape(QFrame.StyledPanel)
        self.frame_encabezado.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.frame_encabezado)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 10, 161, 16))
        self.label.setStyleSheet(u"color:white;")
        self.pushButton_3 = QPushButton(self.frame_encabezado)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(580, 30, 31, 31))
        self.frame_2 = QFrame(self.frame_encabezado)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(509, 10, 121, 21))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.toolButton_CloseP = QToolButton(self.frame_2)
        self.toolButton_CloseP.setObjectName(u"toolButton_CloseP")
        self.toolButton_CloseP.setGeometry(QRect(90, 0, 22, 22))
        icon = QIcon()
        icon.addFile(u"./assets/icon/close-window.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton_CloseP.setIcon(icon)
        self.toolButton_MaxiP = QToolButton(self.frame_2)
        self.toolButton_MaxiP.setObjectName(u"toolButton_MaxiP")
        self.toolButton_MaxiP.setGeometry(QRect(60, 0, 22, 22))
        icon1 = QIcon()
        icon1.addFile(u"./assets/icon/maximize-window.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton_MaxiP.setIcon(icon1)
        self.toolButton_MiniP = QToolButton(self.frame_2)
        self.toolButton_MiniP.setObjectName(u"toolButton_MiniP")
        self.toolButton_MiniP.setGeometry(QRect(30, 0, 22, 22))
        icon2 = QIcon()
        icon2.addFile(u"./assets/icon/minimize-window.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton_MiniP.setIcon(icon2)
        self.toolButton_restaure = QToolButton(self.frame_2)
        self.toolButton_restaure.setObjectName(u"toolButton_restaure")
        self.toolButton_restaure.setGeometry(QRect(60, 0, 22, 22))
        icon3 = QIcon()
        icon3.addFile(u"./assets/icon/restore-window.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton_restaure.setIcon(icon3)
        self.toolButton_restaure.raise_()
        self.toolButton_CloseP.raise_()
        self.toolButton_MaxiP.raise_()
        self.toolButton_MiniP.raise_()
        self.toolButton_Tecni = QToolButton(self.Principal_panel_widget)
        self.toolButton_Tecni.setObjectName(u"toolButton_Tecni")
        self.toolButton_Tecni.setEnabled(True)
        self.toolButton_Tecni.setGeometry(QRect(80, 60, 171, 101))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush)
        brush1 = QBrush(QColor(127, 127, 127, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush1)
        brush2 = QBrush(QColor(170, 170, 170, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush2)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        brush3 = QBrush(QColor(0, 0, 0, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush3)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush)
        brush4 = QBrush(QColor(240, 240, 240, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush4)
        brush5 = QBrush(QColor(227, 227, 227, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush5)
        brush6 = QBrush(QColor(160, 160, 160, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        brush7 = QBrush(QColor(105, 105, 105, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush7)
        brush8 = QBrush(QColor(245, 245, 245, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush8)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush8)
        self.toolButton_Tecni.setPalette(palette)
        icon4 = QIcon()
        icon4.addFile(u"./assets/icon/apoyo-tecnico.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton_Tecni.setIcon(icon4)
        self.toolButton_Tecni.setIconSize(QSize(200, 200))
        self.toolButton_Tecni.setCheckable(False)
        self.toolButton_Tecni.setToolButtonStyle(Qt.ToolButtonIconOnly)
        self.toolButton_Tecni.setAutoRaise(True)
        self.toolButton_Infor = QToolButton(self.Principal_panel_widget)
        self.toolButton_Infor.setObjectName(u"toolButton_Infor")
        self.toolButton_Infor.setGeometry(QRect(370, 60, 171, 101))
        icon5 = QIcon()
        icon5.addFile(u"./assets/icon/reporte.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton_Infor.setIcon(icon5)
        self.toolButton_Infor.setIconSize(QSize(200, 200))
        self.toolButton_Infor.setAutoRaise(True)
        self.toolButton_InqPro = QToolButton(self.Principal_panel_widget)
        self.toolButton_InqPro.setObjectName(u"toolButton_InqPro")
        self.toolButton_InqPro.setGeometry(QRect(80, 210, 171, 101))
        icon6 = QIcon()
        icon6.addFile(u"./assets/icon/trabajo-en-equipo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton_InqPro.setIcon(icon6)
        self.toolButton_InqPro.setIconSize(QSize(200, 200))
        self.toolButton_InqPro.setAutoRaise(True)
        self.toolButton_Ser = QToolButton(self.Principal_panel_widget)
        self.toolButton_Ser.setObjectName(u"toolButton_Ser")
        self.toolButton_Ser.setGeometry(QRect(370, 210, 171, 101))
        icon7 = QIcon()
        icon7.addFile(u"./assets/icon/factura.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton_Ser.setIcon(icon7)
        self.toolButton_Ser.setIconSize(QSize(200, 200))
        self.toolButton_Ser.setAutoRaise(True)
        self.label_Prop = QLabel(self.Principal_panel_widget)
        self.label_Prop.setObjectName(u"label_Prop")
        self.label_Prop.setGeometry(QRect(290, 440, 71, 20))
        self.label_Inf = QLabel(self.Principal_panel_widget)
        self.label_Inf.setObjectName(u"label_Inf")
        self.label_Inf.setGeometry(QRect(440, 170, 51, 16))
        self.label_InqPro = QLabel(self.Principal_panel_widget)
        self.label_InqPro.setObjectName(u"label_InqPro")
        self.label_InqPro.setGeometry(QRect(100, 310, 121, 16))
        self.label_Ser = QLabel(self.Principal_panel_widget)
        self.label_Ser.setObjectName(u"label_Ser")
        self.label_Ser.setGeometry(QRect(430, 310, 61, 20))
        self.toolButton_Pro = QToolButton(self.Principal_panel_widget)
        self.toolButton_Pro.setObjectName(u"toolButton_Pro")
        self.toolButton_Pro.setGeometry(QRect(230, 340, 171, 101))
        icon8 = QIcon()
        icon8.addFile(u"./assets/icon/casa.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton_Pro.setIcon(icon8)
        self.toolButton_Pro.setIconSize(QSize(200, 200))
        self.toolButton_Pro.setAutoRaise(True)
        self.label_Tec = QLabel(self.Principal_panel_widget)
        self.label_Tec.setObjectName(u"label_Tec")
        self.label_Tec.setGeometry(QRect(140, 170, 71, 20))
        self.background_frame = QFrame(self.Principal_panel_widget)
        self.background_frame.setObjectName(u"background_frame")
        self.background_frame.setGeometry(QRect(-10, 30, 641, 441))
        self.background_frame.setMaximumSize(QSize(641, 441))
        self.background_frame.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.background_frame.setFrameShape(QFrame.StyledPanel)
        self.background_frame.setFrameShadow(QFrame.Raised)
        self.background_frame.raise_()
        self.frame_encabezado.raise_()
        self.toolButton_Tecni.raise_()
        self.toolButton_Infor.raise_()
        self.toolButton_InqPro.raise_()
        self.toolButton_Ser.raise_()
        self.label_Prop.raise_()
        self.label_Inf.raise_()
        self.label_InqPro.raise_()
        self.label_Ser.raise_()
        self.toolButton_Pro.raise_()
        self.label_Tec.raise_()

        self.verticalLayout.addWidget(self.Principal_panel_widget)


        self.retranslateUi(Form_mainWindow)

        QMetaObject.connectSlotsByName(Form_mainWindow)
    # setupUi

    def retranslateUi(self, Form_mainWindow):
        Form_mainWindow.setWindowTitle(QCoreApplication.translate("Form_mainWindow", u"Form", None))
        self.label.setText(QCoreApplication.translate("Form_mainWindow", u"Administracion de Alquileres ", None))
        self.pushButton_3.setText(QCoreApplication.translate("Form_mainWindow", u"PushButton", None))
        self.toolButton_CloseP.setText(QCoreApplication.translate("Form_mainWindow", u"...", None))
        self.toolButton_MaxiP.setText(QCoreApplication.translate("Form_mainWindow", u"...", None))
        self.toolButton_MiniP.setText(QCoreApplication.translate("Form_mainWindow", u"...", None))
        self.toolButton_restaure.setText(QCoreApplication.translate("Form_mainWindow", u"...", None))
        self.toolButton_Tecni.setText(QCoreApplication.translate("Form_mainWindow", u"...", None))
        self.toolButton_Infor.setText(QCoreApplication.translate("Form_mainWindow", u"...", None))
        self.toolButton_InqPro.setText(QCoreApplication.translate("Form_mainWindow", u"...", None))
        self.toolButton_Ser.setText(QCoreApplication.translate("Form_mainWindow", u"...", None))
        self.label_Prop.setText(QCoreApplication.translate("Form_mainWindow", u"Propiedades", None))
        self.label_Inf.setText(QCoreApplication.translate("Form_mainWindow", u"Informes", None))
        self.label_InqPro.setText(QCoreApplication.translate("Form_mainWindow", u"Inquilinos/propietarios", None))
        self.label_Ser.setText(QCoreApplication.translate("Form_mainWindow", u"Servicios", None))
        self.toolButton_Pro.setText(QCoreApplication.translate("Form_mainWindow", u"...", None))
        self.label_Tec.setText(QCoreApplication.translate("Form_mainWindow", u"Tecnicos", None))
    # retranslateUi

