# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Propiedad_window.ui'
##
## Created by: Qt User Interface Compiler version 6.3.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDateEdit, QFrame, QHeaderView,
    QLabel, QLineEdit, QPushButton, QRadioButton,
    QSizePolicy, QTableView, QTableWidget, QTableWidgetItem,
    QToolButton, QWidget)

class Ui_Form_Propiedad(object):
    def setupUi(self, Form_Propiedad):
        if not Form_Propiedad.objectName():
            Form_Propiedad.setObjectName(u"Form_Propiedad")
        Form_Propiedad.resize(642, 462)
        Form_Propiedad.setMinimumSize(QSize(642, 462))
        Form_Propiedad.setMaximumSize(QSize(642, 462))
        self.toolButton_Agregarp = QToolButton(Form_Propiedad)
        self.toolButton_Agregarp.setObjectName(u"toolButton_Agregarp")
        self.toolButton_Agregarp.setGeometry(QRect(0, 30, 141, 51))
        self.toolButton_Agregarp.setContextMenuPolicy(Qt.ActionsContextMenu)
        self.toolButton_Agregarp.setStyleSheet(u"background:rgb(255, 255, 255);\n"
"color:rgb(170,0,0);")
        self.toolButton_Verp = QToolButton(Form_Propiedad)
        self.toolButton_Verp.setObjectName(u"toolButton_Verp")
        self.toolButton_Verp.setGeometry(QRect(260, 30, 141, 51))
        self.toolButton_Verp.setStyleSheet(u"background:rgb(255, 255, 255);\n"
"color:rgb(170,0,0);")
        self.toolButton_Editarp = QToolButton(Form_Propiedad)
        self.toolButton_Editarp.setObjectName(u"toolButton_Editarp")
        self.toolButton_Editarp.setGeometry(QRect(130, 30, 141, 51))
        self.toolButton_Editarp.setStyleSheet(u"background:rgb(255, 255, 255);\n"
"color:rgb(170,0,0);")
        self.toolButton_ListaAlquiP = QToolButton(Form_Propiedad)
        self.toolButton_ListaAlquiP.setObjectName(u"toolButton_ListaAlquiP")
        self.toolButton_ListaAlquiP.setGeometry(QRect(390, 30, 141, 51))
        self.toolButton_ListaAlquiP.setStyleSheet(u"background:rgb(255, 255, 255);\n"
"color:rgb(170,0,0);")
        self.toolButton_ListaDispP = QToolButton(Form_Propiedad)
        self.toolButton_ListaDispP.setObjectName(u"toolButton_ListaDispP")
        self.toolButton_ListaDispP.setGeometry(QRect(520, 30, 121, 51))
        self.toolButton_ListaDispP.setStyleSheet(u"background:rgb(255, 255, 255);\n"
"color:rgb(170,0,0);")
        self.line = QFrame(Form_Propiedad)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 75, 641, 21))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.frame_3 = QFrame(Form_Propiedad)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(0, 80, 641, 411))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.label_Prop_Datos = QLabel(self.frame_3)
        self.label_Prop_Datos.setObjectName(u"label_Prop_Datos")
        self.label_Prop_Datos.setGeometry(QRect(0, 10, 71, 16))
        self.label_Prop_Datos.setStyleSheet(u"font: 700 9pt \"Segoe UI\";")
        self.label_calle = QLabel(self.frame_3)
        self.label_calle.setObjectName(u"label_calle")
        self.label_calle.setGeometry(QRect(0, 200, 41, 21))
        self.lineEdit_Ciudad_Popied = QLineEdit(self.frame_3)
        self.lineEdit_Ciudad_Popied.setObjectName(u"lineEdit_Ciudad_Popied")
        self.lineEdit_Ciudad_Popied.setGeometry(QRect(50, 160, 181, 22))
        self.label_altura = QLabel(self.frame_3)
        self.label_altura.setObjectName(u"label_altura")
        self.label_altura.setGeometry(QRect(240, 200, 41, 21))
        self.lineEdit_Altura_Propied = QLineEdit(self.frame_3)
        self.lineEdit_Altura_Propied.setObjectName(u"lineEdit_Altura_Propied")
        self.lineEdit_Altura_Propied.setGeometry(QRect(280, 200, 51, 22))
        self.label_piso = QLabel(self.frame_3)
        self.label_piso.setObjectName(u"label_piso")
        self.label_piso.setGeometry(QRect(440, 200, 31, 21))
        self.lineEdit_Piso_Propied = QLineEdit(self.frame_3)
        self.lineEdit_Piso_Propied.setObjectName(u"lineEdit_Piso_Propied")
        self.lineEdit_Piso_Propied.setGeometry(QRect(490, 200, 51, 22))
        self.label_dpto = QLabel(self.frame_3)
        self.label_dpto.setObjectName(u"label_dpto")
        self.label_dpto.setGeometry(QRect(340, 200, 31, 21))
        self.lineEdit_Comuna_Propied = QLineEdit(self.frame_3)
        self.lineEdit_Comuna_Propied.setObjectName(u"lineEdit_Comuna_Propied")
        self.lineEdit_Comuna_Propied.setGeometry(QRect(490, 160, 51, 22))
        self.label_Ciudad = QLabel(self.frame_3)
        self.label_Ciudad.setObjectName(u"label_Ciudad")
        self.label_Ciudad.setGeometry(QRect(0, 160, 41, 21))
        self.lineEdit_Calle_Propied = QLineEdit(self.frame_3)
        self.lineEdit_Calle_Propied.setObjectName(u"lineEdit_Calle_Propied")
        self.lineEdit_Calle_Propied.setGeometry(QRect(50, 200, 181, 22))
        self.label_Barrio = QLabel(self.frame_3)
        self.label_Barrio.setObjectName(u"label_Barrio")
        self.label_Barrio.setGeometry(QRect(240, 160, 41, 21))
        self.lineEdit_Barrio_Propied = QLineEdit(self.frame_3)
        self.lineEdit_Barrio_Propied.setObjectName(u"lineEdit_Barrio_Propied")
        self.lineEdit_Barrio_Propied.setGeometry(QRect(280, 160, 141, 22))
        self.label_comuna = QLabel(self.frame_3)
        self.label_comuna.setObjectName(u"label_comuna")
        self.label_comuna.setGeometry(QRect(430, 160, 51, 21))
        self.lineEdit_Dpto_Propied = QLineEdit(self.frame_3)
        self.lineEdit_Dpto_Propied.setObjectName(u"lineEdit_Dpto_Propied")
        self.lineEdit_Dpto_Propied.setGeometry(QRect(380, 200, 51, 22))
        self.lineEdit_Nombre_da = QLineEdit(self.frame_3)
        self.lineEdit_Nombre_da.setObjectName(u"lineEdit_Nombre_da")
        self.lineEdit_Nombre_da.setGeometry(QRect(60, 30, 111, 20))
        self.label_nombre_da = QLabel(self.frame_3)
        self.label_nombre_da.setObjectName(u"label_nombre_da")
        self.label_nombre_da.setGeometry(QRect(0, 30, 51, 21))
        self.label_apell_da = QLabel(self.frame_3)
        self.label_apell_da.setObjectName(u"label_apell_da")
        self.label_apell_da.setGeometry(QRect(0, 60, 61, 21))
        self.lineEdit_Apellido_da = QLineEdit(self.frame_3)
        self.lineEdit_Apellido_da.setObjectName(u"lineEdit_Apellido_da")
        self.lineEdit_Apellido_da.setGeometry(QRect(60, 60, 111, 20))
        self.lineEdit_DNI_da = QLineEdit(self.frame_3)
        self.lineEdit_DNI_da.setObjectName(u"lineEdit_DNI_da")
        self.lineEdit_DNI_da.setGeometry(QRect(250, 30, 111, 20))
        self.label_docu_da = QLabel(self.frame_3)
        self.label_docu_da.setObjectName(u"label_docu_da")
        self.label_docu_da.setGeometry(QRect(180, 30, 71, 21))
        self.label_telf_da = QLabel(self.frame_3)
        self.label_telf_da.setObjectName(u"label_telf_da")
        self.label_telf_da.setGeometry(QRect(180, 60, 71, 21))
        self.lineEdit_Telf_da = QLineEdit(self.frame_3)
        self.lineEdit_Telf_da.setObjectName(u"lineEdit_Telf_da")
        self.lineEdit_Telf_da.setGeometry(QRect(250, 60, 111, 20))
        self.label_3 = QLabel(self.frame_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(0, 90, 71, 16))
        self.lineEdit_12 = QLineEdit(self.frame_3)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        self.lineEdit_12.setGeometry(QRect(60, 90, 301, 22))
        self.label_banco_da = QLabel(self.frame_3)
        self.label_banco_da.setObjectName(u"label_banco_da")
        self.label_banco_da.setGeometry(QRect(370, 30, 51, 21))
        self.label_Cbu_da = QLabel(self.frame_3)
        self.label_Cbu_da.setObjectName(u"label_Cbu_da")
        self.label_Cbu_da.setGeometry(QRect(370, 60, 61, 21))
        self.lineEdit_Banco_da = QLineEdit(self.frame_3)
        self.lineEdit_Banco_da.setObjectName(u"lineEdit_Banco_da")
        self.lineEdit_Banco_da.setGeometry(QRect(410, 30, 131, 20))
        self.lineEdit_Cbu_da = QLineEdit(self.frame_3)
        self.lineEdit_Cbu_da.setObjectName(u"lineEdit_Cbu_da")
        self.lineEdit_Cbu_da.setGeometry(QRect(410, 60, 131, 20))
        self.label_Datos_propiedad = QLabel(self.frame_3)
        self.label_Datos_propiedad.setObjectName(u"label_Datos_propiedad")
        self.label_Datos_propiedad.setGeometry(QRect(0, 130, 161, 16))
        self.label_Datos_propiedad.setStyleSheet(u"font: 700 9pt \"Segoe UI\";\n"
"font: 700 9pt \"Segoe UI\";")
        self.label_Servicios_propied = QLabel(self.frame_3)
        self.label_Servicios_propied.setObjectName(u"label_Servicios_propied")
        self.label_Servicios_propied.setEnabled(True)
        self.label_Servicios_propied.setGeometry(QRect(0, 230, 161, 16))
        self.label_Servicios_propied.setStyleSheet(u"font: 700 9pt \"Segoe UI\";\n"
"font: 700 9pt \"Segoe UI\";")
        self.Label_agua = QLabel(self.frame_3)
        self.Label_agua.setObjectName(u"Label_agua")
        self.Label_agua.setGeometry(QRect(20, 250, 51, 21))
        self.label_Luz = QLabel(self.frame_3)
        self.label_Luz.setObjectName(u"label_Luz")
        self.label_Luz.setGeometry(QRect(20, 270, 51, 21))
        self.label_Gas = QLabel(self.frame_3)
        self.label_Gas.setObjectName(u"label_Gas")
        self.label_Gas.setGeometry(QRect(20, 290, 51, 21))
        self.label_ABL = QLabel(self.frame_3)
        self.label_ABL.setObjectName(u"label_ABL")
        self.label_ABL.setGeometry(QRect(20, 310, 51, 21))
        self.radioButton_Agua = QRadioButton(self.frame_3)
        self.radioButton_Agua.setObjectName(u"radioButton_Agua")
        self.radioButton_Agua.setGeometry(QRect(70, 250, 21, 20))
        self.radioButton_Luz = QRadioButton(self.frame_3)
        self.radioButton_Luz.setObjectName(u"radioButton_Luz")
        self.radioButton_Luz.setGeometry(QRect(70, 270, 21, 21))
        self.radioButton_Gas = QRadioButton(self.frame_3)
        self.radioButton_Gas.setObjectName(u"radioButton_Gas")
        self.radioButton_Gas.setGeometry(QRect(70, 290, 21, 21))
        self.radioButton_ABL = QRadioButton(self.frame_3)
        self.radioButton_ABL.setObjectName(u"radioButton_ABL")
        self.radioButton_ABL.setGeometry(QRect(70, 310, 21, 21))
        self.label_INternet = QLabel(self.frame_3)
        self.label_INternet.setObjectName(u"label_INternet")
        self.label_INternet.setGeometry(QRect(120, 250, 51, 21))
        self.label_Telf = QLabel(self.frame_3)
        self.label_Telf.setObjectName(u"label_Telf")
        self.label_Telf.setGeometry(QRect(120, 270, 51, 21))
        self.label_cable = QLabel(self.frame_3)
        self.label_cable.setObjectName(u"label_cable")
        self.label_cable.setGeometry(QRect(120, 290, 51, 21))
        self.label_Calefaccion = QLabel(self.frame_3)
        self.label_Calefaccion.setObjectName(u"label_Calefaccion")
        self.label_Calefaccion.setGeometry(QRect(120, 310, 61, 21))
        self.radioButton_INternet = QRadioButton(self.frame_3)
        self.radioButton_INternet.setObjectName(u"radioButton_INternet")
        self.radioButton_INternet.setGeometry(QRect(190, 250, 21, 20))
        self.radioButton_Telf = QRadioButton(self.frame_3)
        self.radioButton_Telf.setObjectName(u"radioButton_Telf")
        self.radioButton_Telf.setGeometry(QRect(190, 270, 21, 20))
        self.radioButton_Cable = QRadioButton(self.frame_3)
        self.radioButton_Cable.setObjectName(u"radioButton_Cable")
        self.radioButton_Cable.setGeometry(QRect(190, 290, 21, 20))
        self.radioButton_Calef = QRadioButton(self.frame_3)
        self.radioButton_Calef.setObjectName(u"radioButton_Calef")
        self.radioButton_Calef.setGeometry(QRect(190, 310, 21, 20))
        self.line_2 = QFrame(self.frame_3)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(210, 250, 20, 81))
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.label_gym = QLabel(self.frame_3)
        self.label_gym.setObjectName(u"label_gym")
        self.label_gym.setGeometry(QRect(250, 250, 31, 21))
        self.label_solarium = QLabel(self.frame_3)
        self.label_solarium.setObjectName(u"label_solarium")
        self.label_solarium.setGeometry(QRect(250, 270, 51, 21))
        self.label_Parrilla = QLabel(self.frame_3)
        self.label_Parrilla.setObjectName(u"label_Parrilla")
        self.label_Parrilla.setGeometry(QRect(250, 290, 51, 21))
        self.label_Pileta = QLabel(self.frame_3)
        self.label_Pileta.setObjectName(u"label_Pileta")
        self.label_Pileta.setGeometry(QRect(250, 310, 51, 21))
        self.line_3 = QFrame(self.frame_3)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(90, 250, 20, 81))
        self.line_3.setFrameShape(QFrame.VLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.radioButton_Gym = QRadioButton(self.frame_3)
        self.radioButton_Gym.setObjectName(u"radioButton_Gym")
        self.radioButton_Gym.setGeometry(QRect(310, 250, 21, 20))
        self.radioButton_Solarium = QRadioButton(self.frame_3)
        self.radioButton_Solarium.setObjectName(u"radioButton_Solarium")
        self.radioButton_Solarium.setGeometry(QRect(310, 270, 21, 20))
        self.radioButton_Parrilla = QRadioButton(self.frame_3)
        self.radioButton_Parrilla.setObjectName(u"radioButton_Parrilla")
        self.radioButton_Parrilla.setGeometry(QRect(310, 290, 21, 20))
        self.radioButton_Pileta = QRadioButton(self.frame_3)
        self.radioButton_Pileta.setObjectName(u"radioButton_Pileta")
        self.radioButton_Pileta.setGeometry(QRect(310, 310, 21, 20))
        self.radioButton_Ascensor = QRadioButton(self.frame_3)
        self.radioButton_Ascensor.setObjectName(u"radioButton_Ascensor")
        self.radioButton_Ascensor.setGeometry(QRect(450, 250, 21, 20))
        self.line_4 = QFrame(self.frame_3)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(340, 250, 20, 81))
        self.line_4.setFrameShape(QFrame.VLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.label_direccion_Ascen = QLabel(self.frame_3)
        self.label_direccion_Ascen.setObjectName(u"label_direccion_Ascen")
        self.label_direccion_Ascen.setGeometry(QRect(370, 250, 61, 21))
        self.label_Encarg = QLabel(self.frame_3)
        self.label_Encarg.setObjectName(u"label_Encarg")
        self.label_Encarg.setGeometry(QRect(370, 270, 61, 21))
        self.radioButton_Encargado = QRadioButton(self.frame_3)
        self.radioButton_Encargado.setObjectName(u"radioButton_Encargado")
        self.radioButton_Encargado.setGeometry(QRect(450, 270, 21, 20))
        self.label_Vigilan8 = QLabel(self.frame_3)
        self.label_Vigilan8.setObjectName(u"label_Vigilan8")
        self.label_Vigilan8.setGeometry(QRect(370, 290, 61, 21))
        self.radioButton_Vigialancia = QRadioButton(self.frame_3)
        self.radioButton_Vigialancia.setObjectName(u"radioButton_Vigialancia")
        self.radioButton_Vigialancia.setGeometry(QRect(450, 290, 21, 20))
        self.label_Baule = QLabel(self.frame_3)
        self.label_Baule.setObjectName(u"label_Baule")
        self.label_Baule.setGeometry(QRect(370, 310, 61, 21))
        self.radioButton_Baulera = QRadioButton(self.frame_3)
        self.radioButton_Baulera.setObjectName(u"radioButton_Baulera")
        self.radioButton_Baulera.setGeometry(QRect(450, 310, 21, 20))
        self.line_5 = QFrame(self.frame_3)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(480, 250, 20, 81))
        self.line_5.setFrameShape(QFrame.VLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.label_Coche = QLabel(self.frame_3)
        self.label_Coche.setObjectName(u"label_Coche")
        self.label_Coche.setGeometry(QRect(510, 250, 61, 21))
        self.radioButton_Cochera = QRadioButton(self.frame_3)
        self.radioButton_Cochera.setObjectName(u"radioButton_Cochera")
        self.radioButton_Cochera.setGeometry(QRect(580, 250, 21, 20))
        self.label_Porte_Elec = QLabel(self.frame_3)
        self.label_Porte_Elec.setObjectName(u"label_Porte_Elec")
        self.label_Porte_Elec.setGeometry(QRect(510, 270, 71, 21))
        self.radioButton_Port_Elec = QRadioButton(self.frame_3)
        self.radioButton_Port_Elec.setObjectName(u"radioButton_Port_Elec")
        self.radioButton_Port_Elec.setGeometry(QRect(580, 270, 21, 20))
        self.label_expen = QLabel(self.frame_3)
        self.label_expen.setObjectName(u"label_expen")
        self.label_expen.setGeometry(QRect(510, 290, 71, 21))
        self.radioButton_19 = QRadioButton(self.frame_3)
        self.radioButton_19.setObjectName(u"radioButton_19")
        self.radioButton_19.setGeometry(QRect(580, 290, 21, 20))
        self.Agregar_Button = QPushButton(self.frame_3)
        self.Agregar_Button.setObjectName(u"Agregar_Button")
        self.Agregar_Button.setGeometry(QRect(280, 350, 75, 24))
        self.label_Balcon = QLabel(self.frame_3)
        self.label_Balcon.setObjectName(u"label_Balcon")
        self.label_Balcon.setGeometry(QRect(510, 310, 71, 21))
        self.radioButton_Balcon = QRadioButton(self.frame_3)
        self.radioButton_Balcon.setObjectName(u"radioButton_Balcon")
        self.radioButton_Balcon.setGeometry(QRect(580, 310, 21, 20))
        self.tableWidget_agregar = QTableWidget(self.frame_3)
        self.tableWidget_agregar.setObjectName(u"tableWidget_agregar")
        self.tableWidget_agregar.setGeometry(QRect(0, -17, 651, 398))
        self.tableWidget_agregar.setMinimumSize(QSize(651, 398))
        self.tableWidget_agregar.setMaximumSize(QSize(651, 401))
        self.tableWidget = QTableWidget(self.frame_3)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(0, 0, 641, 381))
        self.label_direccion_editarP_2 = QLabel(self.frame_3)
        self.label_direccion_editarP_2.setObjectName(u"label_direccion_editarP_2")
        self.label_direccion_editarP_2.setGeometry(QRect(20, 20, 61, 21))
        self.Direccion_labe_editarl_2 = QLabel(self.frame_3)
        self.Direccion_labe_editarl_2.setObjectName(u"Direccion_labe_editarl_2")
        self.Direccion_labe_editarl_2.setGeometry(QRect(80, 20, 461, 31))
        self.label_Alquiler_edit_2 = QLabel(self.frame_3)
        self.label_Alquiler_edit_2.setObjectName(u"label_Alquiler_edit_2")
        self.label_Alquiler_edit_2.setGeometry(QRect(20, 60, 49, 16))
        self.label_expensas_edit_2 = QLabel(self.frame_3)
        self.label_expensas_edit_2.setObjectName(u"label_expensas_edit_2")
        self.label_expensas_edit_2.setGeometry(QRect(20, 80, 49, 16))
        self.label_Expensaestra_edit_2 = QLabel(self.frame_3)
        self.label_Expensaestra_edit_2.setObjectName(u"label_Expensaestra_edit_2")
        self.label_Expensaestra_edit_2.setGeometry(QRect(20, 100, 61, 31))
        self.lineEdit_Alquiler_edit_2 = QLineEdit(self.frame_3)
        self.lineEdit_Alquiler_edit_2.setObjectName(u"lineEdit_Alquiler_edit_2")
        self.lineEdit_Alquiler_edit_2.setGeometry(QRect(80, 50, 113, 22))
        self.lineEdit_expesnas_edit_2 = QLineEdit(self.frame_3)
        self.lineEdit_expesnas_edit_2.setObjectName(u"lineEdit_expesnas_edit_2")
        self.lineEdit_expesnas_edit_2.setGeometry(QRect(80, 80, 111, 22))
        self.lineEdit_extra_edit_2 = QLineEdit(self.frame_3)
        self.lineEdit_extra_edit_2.setObjectName(u"lineEdit_extra_edit_2")
        self.lineEdit_extra_edit_2.setGeometry(QRect(80, 110, 111, 22))
        self.label_Vencimiento_3 = QLabel(self.frame_3)
        self.label_Vencimiento_3.setObjectName(u"label_Vencimiento_3")
        self.label_Vencimiento_3.setGeometry(QRect(230, 50, 71, 20))
        self.label_Vencimiento_4 = QLabel(self.frame_3)
        self.label_Vencimiento_4.setObjectName(u"label_Vencimiento_4")
        self.label_Vencimiento_4.setGeometry(QRect(230, 80, 71, 20))
        self.label_vencimiento_2 = QLabel(self.frame_3)
        self.label_vencimiento_2.setObjectName(u"label_vencimiento_2")
        self.label_vencimiento_2.setGeometry(QRect(230, 110, 71, 20))
        self.dateEdit_alqulier_edit_2 = QDateEdit(self.frame_3)
        self.dateEdit_alqulier_edit_2.setObjectName(u"dateEdit_alqulier_edit_2")
        self.dateEdit_alqulier_edit_2.setGeometry(QRect(320, 50, 110, 22))
        self.dateEdit_expensas_edit_2 = QDateEdit(self.frame_3)
        self.dateEdit_expensas_edit_2.setObjectName(u"dateEdit_expensas_edit_2")
        self.dateEdit_expensas_edit_2.setGeometry(QRect(320, 80, 110, 22))
        self.dateEdit_extra_edit_2 = QDateEdit(self.frame_3)
        self.dateEdit_extra_edit_2.setObjectName(u"dateEdit_extra_edit_2")
        self.dateEdit_extra_edit_2.setGeometry(QRect(320, 110, 110, 22))
        self.label_recibioPagoEditAEX_2 = QLabel(self.frame_3)
        self.label_recibioPagoEditAEX_2.setObjectName(u"label_recibioPagoEditAEX_2")
        self.label_recibioPagoEditAEX_2.setGeometry(QRect(490, 40, 81, 16))
        self.radioButton_editAlq_2 = QRadioButton(self.frame_3)
        self.radioButton_editAlq_2.setObjectName(u"radioButton_editAlq_2")
        self.radioButton_editAlq_2.setGeometry(QRect(490, 60, 41, 20))
        self.radioButton_editalno_2 = QRadioButton(self.frame_3)
        self.radioButton_editalno_2.setObjectName(u"radioButton_editalno_2")
        self.radioButton_editalno_2.setGeometry(QRect(540, 60, 41, 20))
        self.radioButton_editExp_2 = QRadioButton(self.frame_3)
        self.radioButton_editExp_2.setObjectName(u"radioButton_editExp_2")
        self.radioButton_editExp_2.setGeometry(QRect(490, 80, 41, 20))
        self.radioButton_editexpno_2 = QRadioButton(self.frame_3)
        self.radioButton_editexpno_2.setObjectName(u"radioButton_editexpno_2")
        self.radioButton_editexpno_2.setGeometry(QRect(540, 80, 41, 20))
        self.radioButton_editextra_2 = QRadioButton(self.frame_3)
        self.radioButton_editextra_2.setObjectName(u"radioButton_editextra_2")
        self.radioButton_editextra_2.setGeometry(QRect(490, 100, 41, 20))
        self.radioButton_editextrano_2 = QRadioButton(self.frame_3)
        self.radioButton_editextrano_2.setObjectName(u"radioButton_editextrano_2")
        self.radioButton_editextrano_2.setGeometry(QRect(540, 100, 41, 20))
        self.line_8 = QFrame(self.frame_3)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(0, 130, 641, 31))
        self.line_8.setFrameShape(QFrame.HLine)
        self.line_8.setFrameShadow(QFrame.Sunken)
        self.label_gas_edit_2 = QLabel(self.frame_3)
        self.label_gas_edit_2.setObjectName(u"label_gas_edit_2")
        self.label_gas_edit_2.setGeometry(QRect(10, 160, 21, 16))
        self.lineEdit_13 = QLineEdit(self.frame_3)
        self.lineEdit_13.setObjectName(u"lineEdit_13")
        self.lineEdit_13.setGeometry(QRect(40, 160, 113, 22))
        self.label_Luz_edit_2 = QLabel(self.frame_3)
        self.label_Luz_edit_2.setObjectName(u"label_Luz_edit_2")
        self.label_Luz_edit_2.setGeometry(QRect(10, 190, 21, 16))
        self.lineEdit_16 = QLineEdit(self.frame_3)
        self.lineEdit_16.setObjectName(u"lineEdit_16")
        self.lineEdit_16.setGeometry(QRect(40, 190, 113, 22))
        self.label_agua_edit_2 = QLabel(self.frame_3)
        self.label_agua_edit_2.setObjectName(u"label_agua_edit_2")
        self.label_agua_edit_2.setGeometry(QRect(10, 220, 31, 16))
        self.lineEdit_17 = QLineEdit(self.frame_3)
        self.lineEdit_17.setObjectName(u"lineEdit_17")
        self.lineEdit_17.setGeometry(QRect(40, 220, 113, 22))
        self.label_abl_edir_2 = QLabel(self.frame_3)
        self.label_abl_edir_2.setObjectName(u"label_abl_edir_2")
        self.label_abl_edir_2.setGeometry(QRect(10, 250, 31, 16))
        self.lineEdit_18 = QLineEdit(self.frame_3)
        self.lineEdit_18.setObjectName(u"lineEdit_18")
        self.lineEdit_18.setGeometry(QRect(40, 250, 113, 22))
        self.label_gasedit_2 = QLabel(self.frame_3)
        self.label_gasedit_2.setObjectName(u"label_gasedit_2")
        self.label_gasedit_2.setGeometry(QRect(190, 160, 71, 20))
        self.label_LuzEdit_2 = QLabel(self.frame_3)
        self.label_LuzEdit_2.setObjectName(u"label_LuzEdit_2")
        self.label_LuzEdit_2.setGeometry(QRect(190, 190, 71, 20))
        self.label_AguaEdit_2 = QLabel(self.frame_3)
        self.label_AguaEdit_2.setObjectName(u"label_AguaEdit_2")
        self.label_AguaEdit_2.setGeometry(QRect(190, 220, 71, 20))
        self.label_ABl_edit_2 = QLabel(self.frame_3)
        self.label_ABl_edit_2.setObjectName(u"label_ABl_edit_2")
        self.label_ABl_edit_2.setGeometry(QRect(190, 250, 71, 20))
        self.dateEdit_gas_edit_2 = QDateEdit(self.frame_3)
        self.dateEdit_gas_edit_2.setObjectName(u"dateEdit_gas_edit_2")
        self.dateEdit_gas_edit_2.setGeometry(QRect(270, 160, 110, 22))
        self.dateEdit_luzEdir_2 = QDateEdit(self.frame_3)
        self.dateEdit_luzEdir_2.setObjectName(u"dateEdit_luzEdir_2")
        self.dateEdit_luzEdir_2.setGeometry(QRect(270, 190, 110, 22))
        self.dateEdit_Aguaedit_2 = QDateEdit(self.frame_3)
        self.dateEdit_Aguaedit_2.setObjectName(u"dateEdit_Aguaedit_2")
        self.dateEdit_Aguaedit_2.setGeometry(QRect(270, 220, 110, 22))
        self.dateEdit_ABLEdit_2 = QDateEdit(self.frame_3)
        self.dateEdit_ABLEdit_2.setObjectName(u"dateEdit_ABLEdit_2")
        self.dateEdit_ABLEdit_2.setGeometry(QRect(270, 250, 110, 22))
        self.label_recibiopago_editS_2 = QLabel(self.frame_3)
        self.label_recibiopago_editS_2.setObjectName(u"label_recibiopago_editS_2")
        self.label_recibiopago_editS_2.setGeometry(QRect(480, 150, 81, 16))
        self.radioButton_gas_2 = QRadioButton(self.frame_3)
        self.radioButton_gas_2.setObjectName(u"radioButton_gas_2")
        self.radioButton_gas_2.setGeometry(QRect(470, 180, 41, 20))
        self.radioButtongasno_2 = QRadioButton(self.frame_3)
        self.radioButtongasno_2.setObjectName(u"radioButtongasno_2")
        self.radioButtongasno_2.setGeometry(QRect(530, 180, 41, 20))
        self.radioButton_luz_2 = QRadioButton(self.frame_3)
        self.radioButton_luz_2.setObjectName(u"radioButton_luz_2")
        self.radioButton_luz_2.setGeometry(QRect(470, 200, 41, 20))
        self.radioButton_luzNo_2 = QRadioButton(self.frame_3)
        self.radioButton_luzNo_2.setObjectName(u"radioButton_luzNo_2")
        self.radioButton_luzNo_2.setGeometry(QRect(530, 200, 41, 20))
        self.radioButton_Agua_3 = QRadioButton(self.frame_3)
        self.radioButton_Agua_3.setObjectName(u"radioButton_Agua_3")
        self.radioButton_Agua_3.setGeometry(QRect(470, 220, 41, 20))
        self.radioButton_AguaNo_2 = QRadioButton(self.frame_3)
        self.radioButton_AguaNo_2.setObjectName(u"radioButton_AguaNo_2")
        self.radioButton_AguaNo_2.setGeometry(QRect(530, 220, 41, 20))
        self.radioButton_abl_2 = QRadioButton(self.frame_3)
        self.radioButton_abl_2.setObjectName(u"radioButton_abl_2")
        self.radioButton_abl_2.setGeometry(QRect(470, 240, 41, 20))
        self.radioButton_AblNo_2 = QRadioButton(self.frame_3)
        self.radioButton_AblNo_2.setObjectName(u"radioButton_AblNo_2")
        self.radioButton_AblNo_2.setGeometry(QRect(530, 240, 41, 20))
        self.pushButton_Guardar_4 = QPushButton(self.frame_3)
        self.pushButton_Guardar_4.setObjectName(u"pushButton_Guardar_4")
        self.pushButton_Guardar_4.setGeometry(QRect(290, 320, 101, 24))
        self.background_frame = QFrame(self.frame_3)
        self.background_frame.setObjectName(u"background_frame")
        self.background_frame.setGeometry(QRect(0, -10, 639, 461))
        self.background_frame.setFrameShape(QFrame.StyledPanel)
        self.background_frame.setFrameShadow(QFrame.Raised)
        self.frame_resumen_3 = QFrame(self.background_frame)
        self.frame_resumen_3.setObjectName(u"frame_resumen_3")
        self.frame_resumen_3.setGeometry(QRect(190, 420, 639, 449))
        self.frame_resumen_3.setFrameShape(QFrame.StyledPanel)
        self.frame_resumen_3.setFrameShadow(QFrame.Raised)
        self.label_35 = QLabel(self.frame_resumen_3)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(30, 70, 49, 16))
        self.label_36 = QLabel(self.frame_resumen_3)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(30, 100, 49, 16))
        self.lineEdit_19 = QLineEdit(self.frame_resumen_3)
        self.lineEdit_19.setObjectName(u"lineEdit_19")
        self.lineEdit_19.setGeometry(QRect(100, 100, 113, 22))
        self.lineEdit_20 = QLineEdit(self.frame_resumen_3)
        self.lineEdit_20.setObjectName(u"lineEdit_20")
        self.lineEdit_20.setGeometry(QRect(100, 70, 113, 22))
        self.dateEdit_15 = QDateEdit(self.frame_resumen_3)
        self.dateEdit_15.setObjectName(u"dateEdit_15")
        self.dateEdit_15.setGeometry(QRect(300, 70, 110, 22))
        self.label_37 = QLabel(self.frame_resumen_3)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(220, 70, 71, 20))
        self.label_38 = QLabel(self.frame_resumen_3)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(220, 100, 71, 20))
        self.dateEdit_16 = QDateEdit(self.frame_resumen_3)
        self.dateEdit_16.setObjectName(u"dateEdit_16")
        self.dateEdit_16.setGeometry(QRect(300, 100, 110, 22))
        self.label_39 = QLabel(self.frame_resumen_3)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(30, 130, 81, 31))
        self.lineEdit_21 = QLineEdit(self.frame_resumen_3)
        self.lineEdit_21.setObjectName(u"lineEdit_21")
        self.lineEdit_21.setGeometry(QRect(100, 130, 111, 22))
        self.label_40 = QLabel(self.frame_resumen_3)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(220, 130, 71, 20))
        self.dateEdit_17 = QDateEdit(self.frame_resumen_3)
        self.dateEdit_17.setObjectName(u"dateEdit_17")
        self.dateEdit_17.setGeometry(QRect(300, 130, 110, 22))
        self.radioButton_20 = QRadioButton(self.frame_resumen_3)
        self.radioButton_20.setObjectName(u"radioButton_20")
        self.radioButton_20.setGeometry(QRect(430, 70, 41, 20))
        self.radioButton_30 = QRadioButton(self.frame_resumen_3)
        self.radioButton_30.setObjectName(u"radioButton_30")
        self.radioButton_30.setGeometry(QRect(430, 100, 41, 20))
        self.radioButton_31 = QRadioButton(self.frame_resumen_3)
        self.radioButton_31.setObjectName(u"radioButton_31")
        self.radioButton_31.setGeometry(QRect(430, 130, 41, 20))
        self.radioButton_32 = QRadioButton(self.frame_resumen_3)
        self.radioButton_32.setObjectName(u"radioButton_32")
        self.radioButton_32.setGeometry(QRect(500, 70, 41, 20))
        self.radioButton_33 = QRadioButton(self.frame_resumen_3)
        self.radioButton_33.setObjectName(u"radioButton_33")
        self.radioButton_33.setGeometry(QRect(500, 100, 41, 20))
        self.radioButton_34 = QRadioButton(self.frame_resumen_3)
        self.radioButton_34.setObjectName(u"radioButton_34")
        self.radioButton_34.setGeometry(QRect(500, 130, 41, 20))
        self.label_41 = QLabel(self.frame_resumen_3)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(440, 50, 81, 16))
        self.line_9 = QFrame(self.frame_resumen_3)
        self.line_9.setObjectName(u"line_9")
        self.line_9.setGeometry(QRect(0, 160, 641, 31))
        self.line_9.setFrameShape(QFrame.HLine)
        self.line_9.setFrameShadow(QFrame.Sunken)
        self.label_42 = QLabel(self.frame_resumen_3)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(80, 200, 49, 16))
        self.label_43 = QLabel(self.frame_resumen_3)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(80, 240, 49, 16))
        self.label_44 = QLabel(self.frame_resumen_3)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(80, 280, 49, 16))
        self.label_45 = QLabel(self.frame_resumen_3)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(80, 320, 49, 16))
        self.lineEdit_22 = QLineEdit(self.frame_resumen_3)
        self.lineEdit_22.setObjectName(u"lineEdit_22")
        self.lineEdit_22.setGeometry(QRect(140, 200, 113, 22))
        self.lineEdit_23 = QLineEdit(self.frame_resumen_3)
        self.lineEdit_23.setObjectName(u"lineEdit_23")
        self.lineEdit_23.setGeometry(QRect(140, 240, 113, 22))
        self.lineEdit_24 = QLineEdit(self.frame_resumen_3)
        self.lineEdit_24.setObjectName(u"lineEdit_24")
        self.lineEdit_24.setGeometry(QRect(140, 280, 113, 22))
        self.lineEdit_25 = QLineEdit(self.frame_resumen_3)
        self.lineEdit_25.setObjectName(u"lineEdit_25")
        self.lineEdit_25.setGeometry(QRect(140, 320, 113, 22))
        self.label_46 = QLabel(self.frame_resumen_3)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(290, 200, 71, 20))
        self.label_47 = QLabel(self.frame_resumen_3)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(290, 240, 71, 20))
        self.label_48 = QLabel(self.frame_resumen_3)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(290, 280, 71, 20))
        self.label_49 = QLabel(self.frame_resumen_3)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(290, 320, 71, 20))
        self.dateEdit_18 = QDateEdit(self.frame_resumen_3)
        self.dateEdit_18.setObjectName(u"dateEdit_18")
        self.dateEdit_18.setGeometry(QRect(370, 200, 110, 22))
        self.dateEdit_19 = QDateEdit(self.frame_resumen_3)
        self.dateEdit_19.setObjectName(u"dateEdit_19")
        self.dateEdit_19.setGeometry(QRect(370, 240, 110, 22))
        self.dateEdit_20 = QDateEdit(self.frame_resumen_3)
        self.dateEdit_20.setObjectName(u"dateEdit_20")
        self.dateEdit_20.setGeometry(QRect(370, 280, 110, 22))
        self.dateEdit_21 = QDateEdit(self.frame_resumen_3)
        self.dateEdit_21.setObjectName(u"dateEdit_21")
        self.dateEdit_21.setGeometry(QRect(370, 320, 110, 22))
        self.radioButton_35 = QRadioButton(self.frame_resumen_3)
        self.radioButton_35.setObjectName(u"radioButton_35")
        self.radioButton_35.setGeometry(QRect(500, 200, 41, 20))
        self.radioButton_36 = QRadioButton(self.frame_resumen_3)
        self.radioButton_36.setObjectName(u"radioButton_36")
        self.radioButton_36.setGeometry(QRect(560, 200, 41, 20))
        self.radioButton_37 = QRadioButton(self.frame_resumen_3)
        self.radioButton_37.setObjectName(u"radioButton_37")
        self.radioButton_37.setGeometry(QRect(560, 240, 41, 20))
        self.radioButton_38 = QRadioButton(self.frame_resumen_3)
        self.radioButton_38.setObjectName(u"radioButton_38")
        self.radioButton_38.setGeometry(QRect(560, 280, 41, 20))
        self.radioButton_39 = QRadioButton(self.frame_resumen_3)
        self.radioButton_39.setObjectName(u"radioButton_39")
        self.radioButton_39.setGeometry(QRect(560, 320, 41, 20))
        self.radioButton_40 = QRadioButton(self.frame_resumen_3)
        self.radioButton_40.setObjectName(u"radioButton_40")
        self.radioButton_40.setGeometry(QRect(500, 240, 41, 20))
        self.radioButton_41 = QRadioButton(self.frame_resumen_3)
        self.radioButton_41.setObjectName(u"radioButton_41")
        self.radioButton_41.setGeometry(QRect(500, 280, 41, 20))
        self.radioButton_42 = QRadioButton(self.frame_resumen_3)
        self.radioButton_42.setObjectName(u"radioButton_42")
        self.radioButton_42.setGeometry(QRect(500, 320, 41, 20))
        self.label_50 = QLabel(self.frame_resumen_3)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(500, 180, 81, 16))
        self.pushButton_3 = QPushButton(self.frame_resumen_3)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(60, 390, 101, 24))
        self.pushButton_Guardar_3 = QPushButton(self.background_frame)
        self.pushButton_Guardar_3.setObjectName(u"pushButton_Guardar_3")
        self.pushButton_Guardar_3.setGeometry(QRect(270, 390, 101, 24))
        self.tableWidget_ver = QTableWidget(self.background_frame)
        self.tableWidget_ver.setObjectName(u"tableWidget_ver")
        self.tableWidget_ver.setGeometry(QRect(0, 10, 641, 391))
        self.busqueda_frame_2 = QFrame(self.background_frame)
        self.busqueda_frame_2.setObjectName(u"busqueda_frame_2")
        self.busqueda_frame_2.setGeometry(QRect(0, 20, 631, 81))
        self.busqueda_frame_2.setFrameShape(QFrame.StyledPanel)
        self.busqueda_frame_2.setFrameShadow(QFrame.Raised)
        self.lineEdit_calle_b_3 = QLineEdit(self.busqueda_frame_2)
        self.lineEdit_calle_b_3.setObjectName(u"lineEdit_calle_b_3")
        self.lineEdit_calle_b_3.setGeometry(QRect(80, 10, 121, 22))
        self.label_calle_busqueda_3 = QLabel(self.busqueda_frame_2)
        self.label_calle_busqueda_3.setObjectName(u"label_calle_busqueda_3")
        self.label_calle_busqueda_3.setGeometry(QRect(40, 10, 51, 21))
        self.label_altura_busqueda_3 = QLabel(self.busqueda_frame_2)
        self.label_altura_busqueda_3.setObjectName(u"label_altura_busqueda_3")
        self.label_altura_busqueda_3.setGeometry(QRect(40, 50, 51, 21))
        self.lineEdit_Altura_B_3 = QLineEdit(self.busqueda_frame_2)
        self.lineEdit_Altura_B_3.setObjectName(u"lineEdit_Altura_B_3")
        self.lineEdit_Altura_B_3.setGeometry(QRect(80, 50, 121, 22))
        self.lineEdit_Piso_b_3 = QLineEdit(self.busqueda_frame_2)
        self.lineEdit_Piso_b_3.setObjectName(u"lineEdit_Piso_b_3")
        self.lineEdit_Piso_b_3.setGeometry(QRect(260, 10, 121, 22))
        self.lineEdit_dpto_b_3 = QLineEdit(self.busqueda_frame_2)
        self.lineEdit_dpto_b_3.setObjectName(u"lineEdit_dpto_b_3")
        self.lineEdit_dpto_b_3.setGeometry(QRect(260, 50, 121, 22))
        self.label_piso_Busqueda_3 = QLabel(self.busqueda_frame_2)
        self.label_piso_Busqueda_3.setObjectName(u"label_piso_Busqueda_3")
        self.label_piso_Busqueda_3.setGeometry(QRect(210, 11, 51, 20))
        self.label_5dpto_busqueda_3 = QLabel(self.busqueda_frame_2)
        self.label_5dpto_busqueda_3.setObjectName(u"label_5dpto_busqueda_3")
        self.label_5dpto_busqueda_3.setGeometry(QRect(210, 50, 51, 21))
        self.pushButton_buscar_3 = QPushButton(self.busqueda_frame_2)
        self.pushButton_buscar_3.setObjectName(u"pushButton_buscar_3")
        self.pushButton_buscar_3.setGeometry(QRect(410, 20, 75, 41))
        icon = QIcon()
        icon.addFile(u"../assets/icon/search.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_buscar_3.setIcon(icon)
        self.frame_Result_Ver_3 = QFrame(self.busqueda_frame_2)
        self.frame_Result_Ver_3.setObjectName(u"frame_Result_Ver_3")
        self.frame_Result_Ver_3.setGeometry(QRect(-40, 40, 641, 281))
        self.frame_Result_Ver_3.setFrameShape(QFrame.StyledPanel)
        self.frame_Result_Ver_3.setFrameShadow(QFrame.Raised)
        self.frame_Alquiladas = QFrame(self.background_frame)
        self.frame_Alquiladas.setObjectName(u"frame_Alquiladas")
        self.frame_Alquiladas.setGeometry(QRect(0, 20, 641, 381))
        self.frame_Alquiladas.setFrameShape(QFrame.StyledPanel)
        self.frame_Alquiladas.setFrameShadow(QFrame.Raised)
        self.tableView_Alquiladas = QTableView(self.frame_Alquiladas)
        self.tableView_Alquiladas.setObjectName(u"tableView_Alquiladas")
        self.tableView_Alquiladas.setGeometry(QRect(0, -10, 651, 431))
        self.frame_Disponibles = QFrame(self.frame_Alquiladas)
        self.frame_Disponibles.setObjectName(u"frame_Disponibles")
        self.frame_Disponibles.setGeometry(QRect(0, -10, 641, 381))
        self.frame_Disponibles.setFrameShape(QFrame.StyledPanel)
        self.frame_Disponibles.setFrameShadow(QFrame.Raised)
        self.tableView_disponibles = QTableView(self.frame_Disponibles)
        self.tableView_disponibles.setObjectName(u"tableView_disponibles")
        self.tableView_disponibles.setGeometry(QRect(0, 0, 641, 381))
        self.tableWidget_agregar.raise_()
        self.label_Prop_Datos.raise_()
        self.label_calle.raise_()
        self.lineEdit_Ciudad_Popied.raise_()
        self.label_altura.raise_()
        self.lineEdit_Altura_Propied.raise_()
        self.label_piso.raise_()
        self.lineEdit_Piso_Propied.raise_()
        self.label_dpto.raise_()
        self.lineEdit_Comuna_Propied.raise_()
        self.label_Ciudad.raise_()
        self.lineEdit_Calle_Propied.raise_()
        self.label_Barrio.raise_()
        self.lineEdit_Barrio_Propied.raise_()
        self.label_comuna.raise_()
        self.lineEdit_Dpto_Propied.raise_()
        self.lineEdit_Nombre_da.raise_()
        self.label_nombre_da.raise_()
        self.label_apell_da.raise_()
        self.lineEdit_Apellido_da.raise_()
        self.lineEdit_DNI_da.raise_()
        self.label_docu_da.raise_()
        self.label_telf_da.raise_()
        self.lineEdit_Telf_da.raise_()
        self.label_3.raise_()
        self.lineEdit_12.raise_()
        self.label_banco_da.raise_()
        self.label_Cbu_da.raise_()
        self.lineEdit_Banco_da.raise_()
        self.lineEdit_Cbu_da.raise_()
        self.label_Datos_propiedad.raise_()
        self.label_Servicios_propied.raise_()
        self.Label_agua.raise_()
        self.label_Luz.raise_()
        self.label_Gas.raise_()
        self.label_ABL.raise_()
        self.radioButton_Agua.raise_()
        self.radioButton_Luz.raise_()
        self.radioButton_Gas.raise_()
        self.radioButton_ABL.raise_()
        self.label_INternet.raise_()
        self.label_Telf.raise_()
        self.label_cable.raise_()
        self.label_Calefaccion.raise_()
        self.radioButton_INternet.raise_()
        self.radioButton_Telf.raise_()
        self.radioButton_Cable.raise_()
        self.radioButton_Calef.raise_()
        self.line_2.raise_()
        self.label_gym.raise_()
        self.label_solarium.raise_()
        self.label_Parrilla.raise_()
        self.label_Pileta.raise_()
        self.line_3.raise_()
        self.radioButton_Gym.raise_()
        self.radioButton_Solarium.raise_()
        self.radioButton_Parrilla.raise_()
        self.radioButton_Pileta.raise_()
        self.radioButton_Ascensor.raise_()
        self.line_4.raise_()
        self.label_direccion_Ascen.raise_()
        self.label_Encarg.raise_()
        self.radioButton_Encargado.raise_()
        self.label_Vigilan8.raise_()
        self.radioButton_Vigialancia.raise_()
        self.label_Baule.raise_()
        self.radioButton_Baulera.raise_()
        self.line_5.raise_()
        self.label_Coche.raise_()
        self.radioButton_Cochera.raise_()
        self.label_Porte_Elec.raise_()
        self.radioButton_Port_Elec.raise_()
        self.label_expen.raise_()
        self.radioButton_19.raise_()
        self.Agregar_Button.raise_()
        self.label_Balcon.raise_()
        self.radioButton_Balcon.raise_()
        self.tableWidget.raise_()
        self.label_direccion_editarP_2.raise_()
        self.Direccion_labe_editarl_2.raise_()
        self.label_Alquiler_edit_2.raise_()
        self.label_expensas_edit_2.raise_()
        self.label_Expensaestra_edit_2.raise_()
        self.lineEdit_Alquiler_edit_2.raise_()
        self.lineEdit_expesnas_edit_2.raise_()
        self.lineEdit_extra_edit_2.raise_()
        self.label_Vencimiento_3.raise_()
        self.label_Vencimiento_4.raise_()
        self.label_vencimiento_2.raise_()
        self.dateEdit_alqulier_edit_2.raise_()
        self.dateEdit_expensas_edit_2.raise_()
        self.dateEdit_extra_edit_2.raise_()
        self.label_recibioPagoEditAEX_2.raise_()
        self.radioButton_editAlq_2.raise_()
        self.radioButton_editalno_2.raise_()
        self.radioButton_editExp_2.raise_()
        self.radioButton_editexpno_2.raise_()
        self.radioButton_editextra_2.raise_()
        self.radioButton_editextrano_2.raise_()
        self.line_8.raise_()
        self.label_gas_edit_2.raise_()
        self.lineEdit_13.raise_()
        self.label_Luz_edit_2.raise_()
        self.lineEdit_16.raise_()
        self.label_agua_edit_2.raise_()
        self.lineEdit_17.raise_()
        self.label_abl_edir_2.raise_()
        self.lineEdit_18.raise_()
        self.label_gasedit_2.raise_()
        self.label_LuzEdit_2.raise_()
        self.label_AguaEdit_2.raise_()
        self.label_ABl_edit_2.raise_()
        self.dateEdit_gas_edit_2.raise_()
        self.dateEdit_luzEdir_2.raise_()
        self.dateEdit_Aguaedit_2.raise_()
        self.dateEdit_ABLEdit_2.raise_()
        self.label_recibiopago_editS_2.raise_()
        self.radioButton_gas_2.raise_()
        self.radioButtongasno_2.raise_()
        self.radioButton_luz_2.raise_()
        self.radioButton_luzNo_2.raise_()
        self.radioButton_Agua_3.raise_()
        self.radioButton_AguaNo_2.raise_()
        self.radioButton_abl_2.raise_()
        self.radioButton_AblNo_2.raise_()
        self.pushButton_Guardar_4.raise_()
        self.background_frame.raise_()
        self.frame_encabezado = QFrame(Form_Propiedad)
        self.frame_encabezado.setObjectName(u"frame_encabezado")
        self.frame_encabezado.setGeometry(QRect(0, 0, 641, 31))
        self.frame_encabezado.setMaximumSize(QSize(641, 31))
        self.frame_encabezado.setStyleSheet(u"background:rgb(170, 0, 0)")
        self.frame_encabezado.setFrameShape(QFrame.StyledPanel)
        self.frame_encabezado.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.frame_encabezado)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 10, 161, 16))
        self.label.setStyleSheet(u"color:white;")
        self.frame_2 = QFrame(self.frame_encabezado)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(509, 10, 121, 21))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.toolButton_CloseP = QToolButton(self.frame_2)
        self.toolButton_CloseP.setObjectName(u"toolButton_CloseP")
        self.toolButton_CloseP.setGeometry(QRect(90, 0, 22, 22))
        icon1 = QIcon()
        icon1.addFile(u"./assets/icon/close-window.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton_CloseP.setIcon(icon1)
        self.toolButton_MaxiP = QToolButton(self.frame_2)
        self.toolButton_MaxiP.setObjectName(u"toolButton_MaxiP")
        self.toolButton_MaxiP.setGeometry(QRect(60, 0, 22, 22))
        icon2 = QIcon()
        icon2.addFile(u"./assets/icon/maximize-window.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton_MaxiP.setIcon(icon2)
        self.toolButton_MiniP = QToolButton(self.frame_2)
        self.toolButton_MiniP.setObjectName(u"toolButton_MiniP")
        self.toolButton_MiniP.setGeometry(QRect(30, 0, 22, 22))
        icon3 = QIcon()
        icon3.addFile(u"./assets/icon/minimize-window.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton_MiniP.setIcon(icon3)
        self.toolButton_restaure = QToolButton(self.frame_2)
        self.toolButton_restaure.setObjectName(u"toolButton_restaure")
        self.toolButton_restaure.setGeometry(QRect(60, 0, 22, 22))
        icon4 = QIcon()
        icon4.addFile(u"./assets/icon/restore-window.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton_restaure.setIcon(icon4)
        self.toolButton_restaure.raise_()
        self.toolButton_CloseP.raise_()
        self.toolButton_MaxiP.raise_()
        self.toolButton_MiniP.raise_()

        self.retranslateUi(Form_Propiedad)

        QMetaObject.connectSlotsByName(Form_Propiedad)
    # setupUi

    def retranslateUi(self, Form_Propiedad):
        Form_Propiedad.setWindowTitle(QCoreApplication.translate("Form_Propiedad", u"Form", None))
        self.toolButton_Agregarp.setText(QCoreApplication.translate("Form_Propiedad", u"Agregar", None))
        self.toolButton_Verp.setText(QCoreApplication.translate("Form_Propiedad", u"Ver", None))
        self.toolButton_Editarp.setText(QCoreApplication.translate("Form_Propiedad", u"Editar", None))
        self.toolButton_ListaAlquiP.setText(QCoreApplication.translate("Form_Propiedad", u"Alquiladas", None))
        self.toolButton_ListaDispP.setText(QCoreApplication.translate("Form_Propiedad", u"Disponibles", None))
        self.label_Prop_Datos.setText(QCoreApplication.translate("Form_Propiedad", u" Propietario ", None))
        self.label_calle.setText(QCoreApplication.translate("Form_Propiedad", u" Calle", None))
        self.label_altura.setText(QCoreApplication.translate("Form_Propiedad", u"Altura", None))
        self.label_piso.setText(QCoreApplication.translate("Form_Propiedad", u"Piso", None))
        self.label_dpto.setText(QCoreApplication.translate("Form_Propiedad", u"Dpto", None))
        self.label_Ciudad.setText(QCoreApplication.translate("Form_Propiedad", u" Ciudad", None))
        self.label_Barrio.setText(QCoreApplication.translate("Form_Propiedad", u"Barrio", None))
        self.label_comuna.setText(QCoreApplication.translate("Form_Propiedad", u"Comuna", None))
        self.label_nombre_da.setText(QCoreApplication.translate("Form_Propiedad", u" Nombre", None))
        self.label_apell_da.setText(QCoreApplication.translate("Form_Propiedad", u" Apellido", None))
        self.label_docu_da.setText(QCoreApplication.translate("Form_Propiedad", u"Documento", None))
        self.label_telf_da.setText(QCoreApplication.translate("Form_Propiedad", u"Telefono", None))
        self.label_3.setText(QCoreApplication.translate("Form_Propiedad", u" Direccion", None))
        self.label_banco_da.setText(QCoreApplication.translate("Form_Propiedad", u"Banco", None))
        self.label_Cbu_da.setText(QCoreApplication.translate("Form_Propiedad", u"CBU", None))
        self.label_Datos_propiedad.setText(QCoreApplication.translate("Form_Propiedad", u" Datos de la propiedad", None))
        self.label_Servicios_propied.setText(QCoreApplication.translate("Form_Propiedad", u" Servicios", None))
        self.Label_agua.setText(QCoreApplication.translate("Form_Propiedad", u" Agua", None))
        self.label_Luz.setText(QCoreApplication.translate("Form_Propiedad", u" Luz", None))
        self.label_Gas.setText(QCoreApplication.translate("Form_Propiedad", u" Gas", None))
        self.label_ABL.setText(QCoreApplication.translate("Form_Propiedad", u" ABL", None))
        self.radioButton_Agua.setText("")
        self.radioButton_Luz.setText("")
        self.radioButton_Gas.setText("")
        self.radioButton_ABL.setText("")
        self.label_INternet.setText(QCoreApplication.translate("Form_Propiedad", u"Internet", None))
        self.label_Telf.setText(QCoreApplication.translate("Form_Propiedad", u"Telefono", None))
        self.label_cable.setText(QCoreApplication.translate("Form_Propiedad", u"Cable", None))
        self.label_Calefaccion.setText(QCoreApplication.translate("Form_Propiedad", u"Calefaccion", None))
        self.radioButton_INternet.setText("")
        self.radioButton_Telf.setText("")
        self.radioButton_Cable.setText("")
        self.radioButton_Calef.setText("")
        self.label_gym.setText(QCoreApplication.translate("Form_Propiedad", u"Gym", None))
        self.label_solarium.setText(QCoreApplication.translate("Form_Propiedad", u"Solarium", None))
        self.label_Parrilla.setText(QCoreApplication.translate("Form_Propiedad", u"Parrilla", None))
        self.label_Pileta.setText(QCoreApplication.translate("Form_Propiedad", u"Pileta", None))
        self.radioButton_Gym.setText("")
        self.radioButton_Solarium.setText("")
        self.radioButton_Parrilla.setText("")
        self.radioButton_Pileta.setText("")
        self.radioButton_Ascensor.setText("")
        self.label_direccion_Ascen.setText(QCoreApplication.translate("Form_Propiedad", u"Ascensores", None))
        self.label_Encarg.setText(QCoreApplication.translate("Form_Propiedad", u"Encargado", None))
        self.radioButton_Encargado.setText("")
        self.label_Vigilan8.setText(QCoreApplication.translate("Form_Propiedad", u"Vigilancia", None))
        self.radioButton_Vigialancia.setText("")
        self.label_Baule.setText(QCoreApplication.translate("Form_Propiedad", u"Baulera", None))
        self.radioButton_Baulera.setText("")
        self.label_Coche.setText(QCoreApplication.translate("Form_Propiedad", u"Cochera", None))
        self.radioButton_Cochera.setText("")
        self.label_Porte_Elec.setText(QCoreApplication.translate("Form_Propiedad", u"Portero Elec", None))
        self.radioButton_Port_Elec.setText("")
        self.label_expen.setText(QCoreApplication.translate("Form_Propiedad", u"Expensas", None))
        self.radioButton_19.setText("")
        self.Agregar_Button.setText(QCoreApplication.translate("Form_Propiedad", u"Agregar", None))
        self.label_Balcon.setText(QCoreApplication.translate("Form_Propiedad", u"Balcon", None))
        self.radioButton_Balcon.setText("")
        self.label_direccion_editarP_2.setText(QCoreApplication.translate("Form_Propiedad", u"Direccion", None))
        self.Direccion_labe_editarl_2.setText("")
        self.label_Alquiler_edit_2.setText(QCoreApplication.translate("Form_Propiedad", u"Alquiler", None))
        self.label_expensas_edit_2.setText(QCoreApplication.translate("Form_Propiedad", u"Expensas", None))
        self.label_Expensaestra_edit_2.setText(QCoreApplication.translate("Form_Propiedad", u"ExpenExtra ", None))
        self.label_Vencimiento_3.setText(QCoreApplication.translate("Form_Propiedad", u"Vencimiento", None))
        self.label_Vencimiento_4.setText(QCoreApplication.translate("Form_Propiedad", u"Vencimiento", None))
        self.label_vencimiento_2.setText(QCoreApplication.translate("Form_Propiedad", u"Vencimiento", None))
        self.label_recibioPagoEditAEX_2.setText(QCoreApplication.translate("Form_Propiedad", u"Recibio Pago", None))
        self.radioButton_editAlq_2.setText(QCoreApplication.translate("Form_Propiedad", u"Si", None))
        self.radioButton_editalno_2.setText(QCoreApplication.translate("Form_Propiedad", u"No", None))
        self.radioButton_editExp_2.setText(QCoreApplication.translate("Form_Propiedad", u"Si", None))
        self.radioButton_editexpno_2.setText(QCoreApplication.translate("Form_Propiedad", u"No", None))
        self.radioButton_editextra_2.setText(QCoreApplication.translate("Form_Propiedad", u"Si", None))
        self.radioButton_editextrano_2.setText(QCoreApplication.translate("Form_Propiedad", u"No", None))
        self.label_gas_edit_2.setText(QCoreApplication.translate("Form_Propiedad", u"Gas", None))
        self.label_Luz_edit_2.setText(QCoreApplication.translate("Form_Propiedad", u"Luz", None))
        self.label_agua_edit_2.setText(QCoreApplication.translate("Form_Propiedad", u"Agua", None))
        self.label_abl_edir_2.setText(QCoreApplication.translate("Form_Propiedad", u"ABL", None))
        self.label_gasedit_2.setText(QCoreApplication.translate("Form_Propiedad", u"Vencimiento", None))
        self.label_LuzEdit_2.setText(QCoreApplication.translate("Form_Propiedad", u"Vencimiento", None))
        self.label_AguaEdit_2.setText(QCoreApplication.translate("Form_Propiedad", u"Vencimiento", None))
        self.label_ABl_edit_2.setText(QCoreApplication.translate("Form_Propiedad", u"Vencimiento", None))
        self.label_recibiopago_editS_2.setText(QCoreApplication.translate("Form_Propiedad", u"  Recibio Pago", None))
        self.radioButton_gas_2.setText(QCoreApplication.translate("Form_Propiedad", u"Si", None))
        self.radioButtongasno_2.setText(QCoreApplication.translate("Form_Propiedad", u"No", None))
        self.radioButton_luz_2.setText(QCoreApplication.translate("Form_Propiedad", u"Si", None))
        self.radioButton_luzNo_2.setText(QCoreApplication.translate("Form_Propiedad", u"No", None))
        self.radioButton_Agua_3.setText(QCoreApplication.translate("Form_Propiedad", u"Si", None))
        self.radioButton_AguaNo_2.setText(QCoreApplication.translate("Form_Propiedad", u"No", None))
        self.radioButton_abl_2.setText(QCoreApplication.translate("Form_Propiedad", u"Si", None))
        self.radioButton_AblNo_2.setText(QCoreApplication.translate("Form_Propiedad", u"No", None))
        self.pushButton_Guardar_4.setText(QCoreApplication.translate("Form_Propiedad", u"Guardar ", None))
        self.label_35.setText(QCoreApplication.translate("Form_Propiedad", u"Alquiler", None))
        self.label_36.setText(QCoreApplication.translate("Form_Propiedad", u"Expensas", None))
        self.label_37.setText(QCoreApplication.translate("Form_Propiedad", u"Vencimiento", None))
        self.label_38.setText(QCoreApplication.translate("Form_Propiedad", u"Vencimiento", None))
        self.label_39.setText(QCoreApplication.translate("Form_Propiedad", u"ExpenExtra ", None))
        self.label_40.setText(QCoreApplication.translate("Form_Propiedad", u"Vencimiento", None))
        self.radioButton_20.setText(QCoreApplication.translate("Form_Propiedad", u"Si", None))
        self.radioButton_30.setText(QCoreApplication.translate("Form_Propiedad", u"Si", None))
        self.radioButton_31.setText(QCoreApplication.translate("Form_Propiedad", u"Si", None))
        self.radioButton_32.setText(QCoreApplication.translate("Form_Propiedad", u"No", None))
        self.radioButton_33.setText(QCoreApplication.translate("Form_Propiedad", u"No", None))
        self.radioButton_34.setText(QCoreApplication.translate("Form_Propiedad", u"No", None))
        self.label_41.setText(QCoreApplication.translate("Form_Propiedad", u"Recibio Pago", None))
        self.label_42.setText(QCoreApplication.translate("Form_Propiedad", u"Gas", None))
        self.label_43.setText(QCoreApplication.translate("Form_Propiedad", u"Luz", None))
        self.label_44.setText(QCoreApplication.translate("Form_Propiedad", u"Agua", None))
        self.label_45.setText(QCoreApplication.translate("Form_Propiedad", u"ABL", None))
        self.label_46.setText(QCoreApplication.translate("Form_Propiedad", u"Vencimiento", None))
        self.label_47.setText(QCoreApplication.translate("Form_Propiedad", u"Vencimiento", None))
        self.label_48.setText(QCoreApplication.translate("Form_Propiedad", u"Vencimiento", None))
        self.label_49.setText(QCoreApplication.translate("Form_Propiedad", u"Vencimiento", None))
        self.radioButton_35.setText(QCoreApplication.translate("Form_Propiedad", u"Si", None))
        self.radioButton_36.setText(QCoreApplication.translate("Form_Propiedad", u"No", None))
        self.radioButton_37.setText(QCoreApplication.translate("Form_Propiedad", u"No", None))
        self.radioButton_38.setText(QCoreApplication.translate("Form_Propiedad", u"No", None))
        self.radioButton_39.setText(QCoreApplication.translate("Form_Propiedad", u"No", None))
        self.radioButton_40.setText(QCoreApplication.translate("Form_Propiedad", u"Si", None))
        self.radioButton_41.setText(QCoreApplication.translate("Form_Propiedad", u"Si", None))
        self.radioButton_42.setText(QCoreApplication.translate("Form_Propiedad", u"Si", None))
        self.label_50.setText(QCoreApplication.translate("Form_Propiedad", u"Recibio Pago", None))
        self.pushButton_3.setText(QCoreApplication.translate("Form_Propiedad", u"Imprimir Informe", None))
        self.pushButton_Guardar_3.setText(QCoreApplication.translate("Form_Propiedad", u"Guardar ", None))
        self.label_calle_busqueda_3.setText(QCoreApplication.translate("Form_Propiedad", u"Calle", None))
        self.label_altura_busqueda_3.setText(QCoreApplication.translate("Form_Propiedad", u"Altura", None))
        self.label_piso_Busqueda_3.setText(QCoreApplication.translate("Form_Propiedad", u"Piso", None))
        self.label_5dpto_busqueda_3.setText(QCoreApplication.translate("Form_Propiedad", u"Dpto", None))
        self.pushButton_buscar_3.setText(QCoreApplication.translate("Form_Propiedad", u"Buscar ", None))
        self.label.setText(QCoreApplication.translate("Form_Propiedad", u"Propiedades", None))
        self.toolButton_CloseP.setText(QCoreApplication.translate("Form_Propiedad", u"...", None))
        self.toolButton_MaxiP.setText(QCoreApplication.translate("Form_Propiedad", u"...", None))
        self.toolButton_MiniP.setText(QCoreApplication.translate("Form_Propiedad", u"...", None))
        self.toolButton_restaure.setText(QCoreApplication.translate("Form_Propiedad", u"...", None))
    # retranslateUi

