# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Window_tecnico.ui'
##
## Created by: Qt User Interface Compiler version 6.3.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QHeaderView, QLabel, QLineEdit, QPushButton,
    QSizePolicy, QTableWidget, QTableWidgetItem, QToolButton,
    QVBoxLayout, QWidget)

class Ui_Form_Tecnicos(object):
    def setupUi(self, Form_Tecnicos):
        if not Form_Tecnicos.objectName():
            Form_Tecnicos.setObjectName(u"Form_Tecnicos")
        Form_Tecnicos.resize(640, 260)
        self.background_frame = QFrame(Form_Tecnicos)
        self.background_frame.setObjectName(u"background_frame")
        self.background_frame.setGeometry(QRect(0, 0, 641, 261))
        self.background_frame.setFrameShape(QFrame.StyledPanel)
        self.background_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayoutWidget = QWidget(Form_Tecnicos)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(0, 30, 641, 461))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.frame = QFrame(self.verticalLayoutWidget)
        self.frame.setObjectName(u"frame")
        self.frame.setStyleSheet(u"background:rgb(255, 255, 255);")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.toolButton_Nuevo_Tecnico = QToolButton(self.frame)
        self.toolButton_Nuevo_Tecnico.setObjectName(u"toolButton_Nuevo_Tecnico")
        self.toolButton_Nuevo_Tecnico.setGeometry(QRect(0, 0, 111, 51))
        self.toolButton_Nuevo_Tecnico.setStyleSheet(u"background:rgb(255, 255, 255);\n"
"color:rgb(170,0,0);")
        self.toolButton_Edit_tecni = QToolButton(self.frame)
        self.toolButton_Edit_tecni.setObjectName(u"toolButton_Edit_tecni")
        self.toolButton_Edit_tecni.setGeometry(QRect(0, 60, 111, 51))
        self.toolButton_Edit_tecni.setStyleSheet(u"background:rgb(255, 255, 255);\n"
"color:rgb(170,0,0);")
        self.toolButton_Buscar_Tecnicos = QToolButton(self.frame)
        self.toolButton_Buscar_Tecnicos.setObjectName(u"toolButton_Buscar_Tecnicos")
        self.toolButton_Buscar_Tecnicos.setGeometry(QRect(0, 120, 111, 51))
        self.toolButton_Buscar_Tecnicos.setStyleSheet(u"background:rgb(255, 255, 255);\n"
"color:rgb(170,0,0);")
        self.toolButton_eliminar = QToolButton(self.frame)
        self.toolButton_eliminar.setObjectName(u"toolButton_eliminar")
        self.toolButton_eliminar.setGeometry(QRect(0, 180, 111, 51))
        self.toolButton_eliminar.setStyleSheet(u"background:rgb(255, 255, 255);\n"
"color:rgb(170,0,0);")
        self.line = QFrame(self.frame)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(110, 0, 16, 231))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.tableWidget_tecnicos = QTableWidget(self.frame)
        self.tableWidget_tecnicos.setObjectName(u"tableWidget_tecnicos")
        self.tableWidget_tecnicos.setGeometry(QRect(110, 0, 531, 231))
        self.label_Tecnico_Nombre = QLabel(self.frame)
        self.label_Tecnico_Nombre.setObjectName(u"label_Tecnico_Nombre")
        self.label_Tecnico_Nombre.setGeometry(QRect(130, 10, 51, 21))
        self.label_Tecnico_Apellido = QLabel(self.frame)
        self.label_Tecnico_Apellido.setObjectName(u"label_Tecnico_Apellido")
        self.label_Tecnico_Apellido.setGeometry(QRect(130, 40, 51, 21))
        self.label_Tecnico_telf = QLabel(self.frame)
        self.label_Tecnico_telf.setObjectName(u"label_Tecnico_telf")
        self.label_Tecnico_telf.setGeometry(QRect(130, 70, 51, 21))
        self.label_Tecnico_4 = QLabel(self.frame)
        self.label_Tecnico_4.setObjectName(u"label_Tecnico_4")
        self.label_Tecnico_4.setGeometry(QRect(310, 100, 81, 21))
        font = QFont()
        font.setBold(True)
        self.label_Tecnico_4.setFont(font)
        self.checkBox_Plomeria = QCheckBox(self.frame)
        self.checkBox_Plomeria.setObjectName(u"checkBox_Plomeria")
        self.checkBox_Plomeria.setGeometry(QRect(260, 130, 76, 20))
        self.checkBox_electri = QCheckBox(self.frame)
        self.checkBox_electri.setObjectName(u"checkBox_electri")
        self.checkBox_electri.setGeometry(QRect(260, 150, 76, 20))
        self.checkBox_Gas = QCheckBox(self.frame)
        self.checkBox_Gas.setObjectName(u"checkBox_Gas")
        self.checkBox_Gas.setGeometry(QRect(260, 170, 76, 20))
        self.checkBox_Albail = QCheckBox(self.frame)
        self.checkBox_Albail.setObjectName(u"checkBox_Albail")
        self.checkBox_Albail.setGeometry(QRect(410, 130, 76, 20))
        self.checkBox_Empape = QCheckBox(self.frame)
        self.checkBox_Empape.setObjectName(u"checkBox_Empape")
        self.checkBox_Empape.setGeometry(QRect(410, 150, 101, 20))
        self.checkBox_AireAcon = QCheckBox(self.frame)
        self.checkBox_AireAcon.setObjectName(u"checkBox_AireAcon")
        self.checkBox_AireAcon.setGeometry(QRect(410, 170, 131, 20))
        self.lineEdit_Nombre_Tecn = QLineEdit(self.frame)
        self.lineEdit_Nombre_Tecn.setObjectName(u"lineEdit_Nombre_Tecn")
        self.lineEdit_Nombre_Tecn.setGeometry(QRect(190, 10, 141, 22))
        self.lineEdit_Apellido_tecn = QLineEdit(self.frame)
        self.lineEdit_Apellido_tecn.setObjectName(u"lineEdit_Apellido_tecn")
        self.lineEdit_Apellido_tecn.setGeometry(QRect(190, 40, 141, 22))
        self.lineEdit_Telefono_Tecn = QLineEdit(self.frame)
        self.lineEdit_Telefono_Tecn.setObjectName(u"lineEdit_Telefono_Tecn")
        self.lineEdit_Telefono_Tecn.setGeometry(QRect(190, 70, 141, 22))
        self.label_Tecn_Horario = QLabel(self.frame)
        self.label_Tecn_Horario.setObjectName(u"label_Tecn_Horario")
        self.label_Tecn_Horario.setGeometry(QRect(400, 10, 51, 21))
        self.label_Tecn_Horario.setFont(font)
        self.label_Tecnico_6 = QLabel(self.frame)
        self.label_Tecnico_6.setObjectName(u"label_Tecnico_6")
        self.label_Tecnico_6.setGeometry(QRect(390, 230, 51, 21))
        self.label_Tec_horarioM = QLabel(self.frame)
        self.label_Tec_horarioM.setObjectName(u"label_Tec_horarioM")
        self.label_Tec_horarioM.setGeometry(QRect(400, 40, 51, 21))
        self.label_TecnHora_T = QLabel(self.frame)
        self.label_TecnHora_T.setObjectName(u"label_TecnHora_T")
        self.label_TecnHora_T.setGeometry(QRect(400, 70, 41, 21))
        self.lineEdit_Horario_Maana = QLineEdit(self.frame)
        self.lineEdit_Horario_Maana.setObjectName(u"lineEdit_Horario_Maana")
        self.lineEdit_Horario_Maana.setGeometry(QRect(450, 40, 141, 22))
        self.lineEdit_Horario_Tarde = QLineEdit(self.frame)
        self.lineEdit_Horario_Tarde.setObjectName(u"lineEdit_Horario_Tarde")
        self.lineEdit_Horario_Tarde.setGeometry(QRect(450, 70, 141, 22))
        self.toolButton_Agrega_tecnicos = QToolButton(self.frame)
        self.toolButton_Agrega_tecnicos.setObjectName(u"toolButton_Agrega_tecnicos")
        self.toolButton_Agrega_tecnicos.setGeometry(QRect(310, 190, 81, 31))
        self.toolButton_Guardar_tecnicos_ = QToolButton(self.frame)
        self.toolButton_Guardar_tecnicos_.setObjectName(u"toolButton_Guardar_tecnicos_")
        self.toolButton_Guardar_tecnicos_.setGeometry(QRect(310, 190, 81, 31))
        self.frame__Buscar_tecnico = QFrame(self.frame)
        self.frame__Buscar_tecnico.setObjectName(u"frame__Buscar_tecnico")
        self.frame__Buscar_tecnico.setGeometry(QRect(110, 0, 531, 231))
        self.frame__Buscar_tecnico.setFrameShape(QFrame.StyledPanel)
        self.frame__Buscar_tecnico.setFrameShadow(QFrame.Raised)
        self.comboBox = QComboBox(self.frame__Buscar_tecnico)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(20, 10, 191, 22))
        self.toolButton = QToolButton(self.frame__Buscar_tecnico)
        self.toolButton.setObjectName(u"toolButton")
        self.toolButton.setGeometry(QRect(220, 10, 22, 22))
        self.toolButton.setStyleSheet(u"background:rgb(170, 0, 0)")
        icon = QIcon()
        icon.addFile(u"./assets/icon/search.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton.setIcon(icon)
        self.frame_Listatenicos = QFrame(self.frame__Buscar_tecnico)
        self.frame_Listatenicos.setObjectName(u"frame_Listatenicos")
        self.frame_Listatenicos.setGeometry(QRect(10, 0, 521, 231))
        self.frame_Listatenicos.setFrameShape(QFrame.StyledPanel)
        self.frame_Listatenicos.setFrameShadow(QFrame.Raised)
        self.frame_Listatenicos.raise_()
        self.comboBox.raise_()
        self.toolButton.raise_()

        self.verticalLayout.addWidget(self.frame)

        self.frame_encabezado = QFrame(Form_Tecnicos)
        self.frame_encabezado.setObjectName(u"frame_encabezado")
        self.frame_encabezado.setGeometry(QRect(0, 0, 641, 31))
        self.frame_encabezado.setMaximumSize(QSize(641, 31))
        self.frame_encabezado.setStyleSheet(u"background:rgb(170, 0, 0)")
        self.frame_encabezado.setFrameShape(QFrame.StyledPanel)
        self.frame_encabezado.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.frame_encabezado)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 10, 161, 16))
        self.label.setStyleSheet(u"color:white;")
        self.pushButton_3 = QPushButton(self.frame_encabezado)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(580, 30, 31, 31))
        self.frame_2 = QFrame(self.frame_encabezado)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(509, 10, 121, 21))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.toolButton_CloseP = QToolButton(self.frame_2)
        self.toolButton_CloseP.setObjectName(u"toolButton_CloseP")
        self.toolButton_CloseP.setGeometry(QRect(90, 0, 22, 22))
        icon1 = QIcon()
        icon1.addFile(u"./assets/icon/close-window.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton_CloseP.setIcon(icon1)
        self.toolButton_MaxiP = QToolButton(self.frame_2)
        self.toolButton_MaxiP.setObjectName(u"toolButton_MaxiP")
        self.toolButton_MaxiP.setGeometry(QRect(60, 0, 22, 22))
        icon2 = QIcon()
        icon2.addFile(u"./assets/icon/maximize-window.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton_MaxiP.setIcon(icon2)
        self.toolButton_MiniP = QToolButton(self.frame_2)
        self.toolButton_MiniP.setObjectName(u"toolButton_MiniP")
        self.toolButton_MiniP.setGeometry(QRect(30, 0, 22, 22))
        icon3 = QIcon()
        icon3.addFile(u"./assets/icon/minimize-window.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton_MiniP.setIcon(icon3)
        self.toolButton_restaure = QToolButton(self.frame_2)
        self.toolButton_restaure.setObjectName(u"toolButton_restaure")
        self.toolButton_restaure.setGeometry(QRect(60, 0, 22, 22))
        icon4 = QIcon()
        icon4.addFile(u"./assets/icon/restore-window.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton_restaure.setIcon(icon4)
        self.toolButton_restaure.raise_()
        self.toolButton_CloseP.raise_()
        self.toolButton_MaxiP.raise_()
        self.toolButton_MiniP.raise_()
        
        self.retranslateUi(Form_Tecnicos)

        QMetaObject.connectSlotsByName(Form_Tecnicos)
    # setupUi

    def retranslateUi(self, Form_Tecnicos):
        Form_Tecnicos.setWindowTitle(QCoreApplication.translate("Form_Tecnicos", u"Form", None))
        self.toolButton_Nuevo_Tecnico.setText(QCoreApplication.translate("Form_Tecnicos", u"Nuevo", None))
        self.toolButton_Edit_tecni.setText(QCoreApplication.translate("Form_Tecnicos", u"Editar", None))
        self.toolButton_Buscar_Tecnicos.setText(QCoreApplication.translate("Form_Tecnicos", u"Buscar", None))
        self.toolButton_eliminar.setText(QCoreApplication.translate("Form_Tecnicos", u"Eliminar", None))
        self.label_Tecnico_Nombre.setText(QCoreApplication.translate("Form_Tecnicos", u"Nombre", None))
        self.label_Tecnico_Apellido.setText(QCoreApplication.translate("Form_Tecnicos", u"Apellido", None))
        self.label_Tecnico_telf.setText(QCoreApplication.translate("Form_Tecnicos", u"Telefono", None))
        self.label_Tecnico_4.setText(QCoreApplication.translate("Form_Tecnicos", u"Especialidad", None))
        self.checkBox_Plomeria.setText(QCoreApplication.translate("Form_Tecnicos", u"Plomeria", None))
        self.checkBox_electri.setText(QCoreApplication.translate("Form_Tecnicos", u"electricidad", None))
        self.checkBox_Gas.setText(QCoreApplication.translate("Form_Tecnicos", u"Gas", None))
        self.checkBox_Albail.setText(QCoreApplication.translate("Form_Tecnicos", u"Albanil", None))
        self.checkBox_Empape.setText(QCoreApplication.translate("Form_Tecnicos", u"Empapelador", None))
        self.checkBox_AireAcon.setText(QCoreApplication.translate("Form_Tecnicos", u"Aire Acondicionado", None))
        self.label_Tecn_Horario.setText(QCoreApplication.translate("Form_Tecnicos", u"Horario", None))
        self.label_Tecnico_6.setText(QCoreApplication.translate("Form_Tecnicos", u"Nombre", None))
        self.label_Tec_horarioM.setText(QCoreApplication.translate("Form_Tecnicos", u"Ma\u00f1ana", None))
        self.label_TecnHora_T.setText(QCoreApplication.translate("Form_Tecnicos", u"Tarde", None))
        self.toolButton_Agrega_tecnicos.setText(QCoreApplication.translate("Form_Tecnicos", u"Agregar", None))
        self.toolButton_Guardar_tecnicos_.setText(QCoreApplication.translate("Form_Tecnicos", u"Guardar", None))
        self.toolButton.setText(QCoreApplication.translate("Form_Tecnicos", u"...", None))
        self.label.setText(QCoreApplication.translate("Form_Tecnicos", u"Tecnicos", None))
        self.pushButton_3.setText(QCoreApplication.translate("Form_Tecnicos", u"PushButton", None))
        self.toolButton_CloseP.setText(QCoreApplication.translate("Form_Tecnicos", u"...", None))
        self.toolButton_MaxiP.setText(QCoreApplication.translate("Form_Tecnicos", u"...", None))
        self.toolButton_MiniP.setText(QCoreApplication.translate("Form_Tecnicos", u"...", None))
        self.toolButton_restaure.setText(QCoreApplication.translate("Form_Tecnicos", u"...", None))
    # retranslateUi

